const playArea = document.getElementById("playArea");
document.body.addEventListener('keydown', keyPress);

var P = {x: -1, y: -1};
var tileType;
var boxCollection = [];
let boxIteration = 0;
var boxPos = {x: -1, y: -1};


/*   Enum of CSS Classes for the static elements   */
var Tiles = {
  Wall: "tile-wall",
  Space: "tile-space",
  Goal: "tile-goal",
};

/*   Enum of CSS Classes for the moving elements   */
var Entities = {
  Character: "entity-player",
  Block: "entity-block",
  BlockDone: "entity-block-goal",
};

/*  Legend
    W = Wall
    B = Movable block
    P = Player starting position
    G = Goal area for the blocks
*/

var tileMap01 = {
  width: 19,
  height: 16,
  mapGrid: [
    [
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      ["W"],
      [" "],
      [" "],
      [" "],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      ["W"],
      ["B"],
      [" "],
      [" "],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      [" "],
      [" "],
      ["B"],
      ["W"],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      ["W"],
      [" "],
      [" "],
      ["B"],
      [" "],
      ["B"],
      [" "],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      ["W"],
      ["W"],
      ["W"],
      [" "],
      ["W"],
      [" "],
      ["W"],
      ["W"],
      [" "],
      ["W"],
      [" "],
      [" "],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
    ],
    [
      ["W"],
      [" "],
      [" "],
      [" "],
      ["W"],
      [" "],
      ["W"],
      ["W"],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      [" "],
      [" "],
      ["G"],
      ["G"],
      ["W"],
    ],
    [
      ["W"],
      [" "],
      ["B"],
      [" "],
      [" "],
      ["B"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      ["G"],
      ["G"],
      ["W"],
    ],
    [
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      [" "],
      ["W"],
      ["P"],
      ["W"],
      ["W"],
      [" "],
      [" "],
      ["G"],
      ["G"],
      ["W"],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
    [
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
      [" "],
    ],
  ],
};

var tileMap02 = {
  width: 19,
  height: 16,
  mapGrid: [
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["B"],
      ["A"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["A"],
      ["B"],
      ["W"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["B"],
      ["A"],
      ["B"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["W"],
      ["A"],
      ["W"],
      ["W"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
    ],
    [
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["A"],
      ["W"],
      ["W"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["A"],
      ["G"],
      ["G"],
      ["W"],
    ],
    [
      ["W"],
      ["A"],
      ["B"],
      ["A"],
      ["A"],
      ["B"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["G"],
      ["G"],
      ["W"],
    ],
    [
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["W"],
      ["P"],
      ["W"],
      ["W"],
      ["A"],
      ["A"],
      ["G"],
      ["G"],
      ["W"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["W"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
    [
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
      ["A"],
    ],
  ],
};

function renderMap() 
{
	for(let col=0; col < tileMap01.height; col++)
	{
		for(let row=0; row < tileMap01.width; row++)
		{
			var element = document.createElement("div");
			element.classList.add("block");
			if(tileMap01.mapGrid[col][row][0] !== " ")
			{
				tileType = tileMap01.mapGrid[col][row][0];
				if(tileType === "B")
				{
					boxPos.x = row;
					boxPos.y = col;

					boxCollection.push(boxPos);
					boxIteration++
				}
				if(tileType === "P")
				{
					P.x = col;
					P.y = row;
				}
				element.classList.add(tileType);
			}
			element.id = "x" + row + "y" + col;
			playArea.appendChild(element);
		}
	}
}


function keyPress(e)
{
  switch(e.key)
  {
    case 'ArrowUp':
      movePlayer(0, -1)
    break;

    case 'ArrowDown':
      movePlayer(0, 1)
    break;

    case 'ArrowLeft':
      movePlayer(-1, 0)
    break;

    case 'ArrowRight':
      movePlayer(1, 0)
    break;

    default:
    break;
  }
}

function movePlayer(x, y)
{
  var newPx = P.x + x;
  var newPy = P.y + y;
  var newBx = P.x + (x*2);
  var newBy = P.y + (y*2);

  var playerElement = document.getElementById("x" + P.x + "y" + P.y);
  var destination = document.getElementById("x" + newPx + "y" + newPy);
  var boxDestination = document.getElementById("x" + newBx + "y" + newBy);
  var tileCompare = tileMap01.mapGrid[newPy][newPx][0];

  if(tileCompare !== "W" && tileCompare !== "B")
  {

    playerElement.classList.remove("P");
    destination.classList.add("P");
    P.x = newPx;
    P.y = newPy;
  }
  else if(tileCompare === "B")
  {
    console.log(destination.x, destination.y, newPx, newPy)
    tileMap01.mapGrid[newPx][newPy].splice(0, 1, "P");
    tileMap01.mapGrid[newBx][newBy].splice(0, 1, "B");
    console.log(tileCompare);
    destination.classList.remove("B");
    boxDestination.classList.add("B");
    playerElement.classList.remove("P");
    destination.classList.add("P");
    P.x = newPx;
    P.y = newPy;
  }
}

renderMap();
